name: Docker Image CI

on:
  push:
    branches: ["main" ]

jobs:
  build:
    name: 构建并推送
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 登陆dockerhub
      uses: docker/login-action@v3
      with:
        username: jadeproheshan
        password: ${{ secrets.SECRET }}

    - name: 构建并推送
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: bbg/debate-website:lateset
