name: Docker Image CI

on:
  push:
    branches: ["main" ]

jobs:
  build:
    name: 构建并推送
    runs-on: ubuntu-latest

    steps:
    - name: 读取仓库内容
      uses: actions/checkout@v4

    - name: 登陆dockerhub
      uses: docker/login-action@v3
      with:
        username: jadeproheshan
        password: ${{ secrets.SECRET }}

    - name: 构建并推送
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: jadeproheshan/debatewebsite:v0.9
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/debate-website
            docker compose pull
            docker compose up -d
            docker image prune -af
